[package]
name = "cargo-compat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
cargo_metadata = "0.19.1"
clap = { version = "4.5.26", features = ["derive"] }
syn = { version = "2.0.96", features = ["full", "extra-traits"] }
